### ISSUE TITLE
Worldmap part 2

### ISSUE THREAD

**Issue by ChristophLasinger** [if-03-01-C-fall-2019/webapp-weather-lasinger-kern#1]
Philip will work on the worldmap itself, which means presenting the map, moving around the map, presenting the weather-related data, etc.
Part 1:https://github.com/if-03-01-C-fall-2019/webapp-weather-lasinger-kern/issues/2#issue-613281249

**Comment by bauepete** [comment]
I would avoid to put the name of the assignee into the description.
