### ISSUE TITLE
Search function part 1

### ISSUE THREAD

**Issue by ChristophLasinger** [if-03-01-C-fall-2019/webapp-weather-lasinger-kern#3]
I (Lasinger Christoph) will work on processing the input(user)- and output(API)- data. I will do this by following one of the tutorials I have found (I´m currently not sure which code I will end up using). 
Part 2: https://github.com/if-03-01-C-fall-2019/webapp-weather-lasinger-kern/issues/4#issue-617549627

**Comment by bauepete** [comment]
What do you mean exactly here? To transfer the user data to the openweathermap api and the result of the openweathermap map api back to the frontend?
